### ISSUE TITLE
After the end of the game, sometimes chess.com prompts a login page , which makes the program crash

### ISSUE THREAD

**Issue by namidaka** [verdie-g/twitch-plays-chessdotcom#9]
![image](https://user-images.githubusercontent.com/47090987/143623391-cb5ff867-b2a9-40b1-9765-3ffc3b0c6907.png)
![image](https://user-images.githubusercontent.com/47090987/143623396-3adc27db-6040-4b3b-ba09-510743e5d22c.png)

**Comment by verdie-g** [comment]
https://github.com/verdie-g/twitch-plays-chess/commit/b5c3dbb42048ca5239a7a298560a4f1ab1df69cd may solve this.
